android.dependency.useConstraints=true
android.enableBuildConfigAsBytecode=false
android.enableJetifier=false
android.enableR8.fullMode=true
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
android.nonTransitiveRClass=true
android.r8.strictFullModeForKeepRules=false
android.uniquePackageNames=false
android.useAndroidX=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx5120m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.tooling.parallel=true
org.gradle.unsafe.configuration-cache=true
org.gradle.warning.mode=all